content_encoder:
  # Optional: mld_vae, vposert_vae
  target: rfmotion.models.architectures.content_encoder.MldVae
  params:
    arch: 'encoder_decoder'
    ff_size: 1024
    num_layers: 9
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    position_embedding: 'learned'
    latent_dim: [7, 256]
    nfeats: 263
    ablation: 
      SKIP_CONNECT: True
      PE_TYPE: mld
      DIFF_PE_TYPE: mld