motion_vae:
  target: rfmotion.models.architectures.rfmotion_vae_nativerope.MldVae # rfmotion_vae.RFMotionVae # mld_vae.MldVae
  params:
    ff_size: 1024
    num_layers: 9
    num_heads: 8
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NFEATS}
    ablation: ${TRAIN.ABLATION}
